name: Cartype Book
favicon: null
layout_spectrum: 0
typography_spectrum: 0.93315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.35297663044184446
  lightness: 0.9139595367014408
  saturation: 0.8107126206159592
  rhythmicContrast: 0.16611761855892837
purpose: []
