name: Cartype Book
favicon: null
layout_spectrum: 0.21643
typography_spectrum: 0.93315
title: Cartype Book
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffde9'
    - '#000000'
    - '#c8c9cb'
    - '#676762'
    - '#42413d'
  brandStrength: 0.35297663044184446
  lightness: 0.9139595367014408
  saturation: 0.8107126206159592
  rhythmicContrast: 0.16611761855892837
purpose: []
